In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
ds=pd.read_csv('dataset.csv')

In [4]:
ds.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0   
1  ...                         4            80                 1   
2  ...                         2            80                 0   
3  ...                         3            80                 0   
4  ...                         4            80                 1   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6   
1                 10                      3               3              10   
2                  7                      3               3               0   
3                  8                      3               3               8   
4                  6                      3               3               2   

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                  4                        0                     5  
1                  7                        1                     7  
2                  0                        0                     0  
3                  7                        3                     0  
4                  2                        2                     2  

[5 rows x 35 columns]

In [5]:
ds.shape

(1470, 35)

In [6]:
ds.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [7]:
cols=['Age', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'Attrition']

In [8]:
ds=ds[cols]

In [9]:
ds

Age     BusinessTravel  DailyRate              Department  \
0      41      Travel_Rarely       1102                   Sales   
1      49  Travel_Frequently        279  Research & Development   
2      37      Travel_Rarely       1373  Research & Development   
3      33  Travel_Frequently       1392  Research & Development   
4      27      Travel_Rarely        591  Research & Development   
5      32  Travel_Frequently       1005  Research & Development   
6      59      Travel_Rarely       1324  Research & Development   
7      30      Travel_Rarely       1358  Research & Development   
8      38  Travel_Frequently        216  Research & Development   
9      36      Travel_Rarely       1299  Research & Development   
10     35      Travel_Rarely        809  Research & Development   
11     29      Travel_Rarely        153  Research & Development   
12     31      Travel_Rarely        670  Research & Development   
13     34      Travel_Rarely       1346  Research & Development   
14     28      Travel_Rarely        103  Research & Development   
15     29      Travel_Rarely       1389  Research & Development   
16     32      Travel_Rarely        334  Research & Development   
17     22         Non-Travel       1123  Research & Development   
18     53      Travel_Rarely       1219                   Sales   
19     38      Travel_Rarely        371  Research & Development   
20     24         Non-Travel        673  Research & Development   
21     36      Travel_Rarely       1218                   Sales   
22     34      Travel_Rarely        419  Research & Development   
23     21      Travel_Rarely        391  Research & Development   
24     34      Travel_Rarely        699  Research & Development   
25     53      Travel_Rarely       1282  Research & Development   
26     32  Travel_Frequently       1125  Research & Development   
27     42      Travel_Rarely        691                   Sales   
28     44      Travel_Rarely        477  Research & Development   
29     46      Travel_Rarely        705                   Sales   
...   ...                ...        ...                     ...   
1440   36  Travel_Frequently        688  Research & Development   
1441   56         Non-Travel        667  Research & Development   
1442   29      Travel_Rarely       1092  Research & Development   
1443   42      Travel_Rarely        300  Research & Development   
1444   56      Travel_Rarely        310  Research & Development   
1445   41      Travel_Rarely        582  Research & Development   
1446   34      Travel_Rarely        704                   Sales   
1447   36         Non-Travel        301                   Sales   
1448   41      Travel_Rarely        930                   Sales   
1449   32      Travel_Rarely        529  Research & Development   
1450   35      Travel_Rarely       1146         Human Resources   
1451   38      Travel_Rarely        345                   Sales   
1452   50  Travel_Frequently        878                   Sales   
1453   36      Travel_Rarely       1120                   Sales   
1454   45      Travel_Rarely        374                   Sales   
1455   40      Travel_Rarely       1322  Research & Development   
1456   35  Travel_Frequently       1199  Research & Development   
1457   40      Travel_Rarely       1194  Research & Development   
1458   35      Travel_Rarely        287  Research & Development   
1459   29      Travel_Rarely       1378  Research & Development   
1460   29      Travel_Rarely        468  Research & Development   
1461   50      Travel_Rarely        410                   Sales   
1462   39      Travel_Rarely        722                   Sales   
1463   31         Non-Travel        325  Research & Development   
1464   26      Travel_Rarely       1167                   Sales   
1465   36  Travel_Frequently        884  Research & Development   
1466   39      Travel_Rarely        613  Research & Development   
1467   27      Travel_Rarely        155  Research & D

In [10]:
ds.isnull().values.any()


False

In [11]:
print (ds.isna().any(axis=0))

Age                         False
BusinessTravel              False
DailyRate                   False
Department                  False
DistanceFromHome            False
Education                   False
EducationField              False
EmployeeCount               False
EmployeeNumber              False
EnvironmentSatisfaction     False
Gender                      False
HourlyRate                  False
JobInvolvement              False
JobLevel                    False
JobRole                     False
JobSatisfaction             False
MaritalStatus               False
MonthlyIncome               False
MonthlyRate                 False
NumCompaniesWorked          False
Over18                      False
OverTime                    False
PercentSalaryHike           False
PerformanceRating           False
RelationshipSatisfaction    False
StandardHours               False
StockOptionLevel            False
TotalWorkingYears           False
TrainingTimesLastYear       False
WorkLifeBalanc

In [12]:
x=ds.iloc[:,0:34].values

In [13]:
y=ds.iloc[:,34:35].values

In [14]:
x

array([[41, 'Travel_Rarely', 1102, ..., 4, 0, 5],
       [49, 'Travel_Frequently', 279, ..., 7, 1, 7],
       [37, 'Travel_Rarely', 1373, ..., 0, 0, 0],
       ...,
       [27, 'Travel_Rarely', 155, ..., 2, 0, 3],
       [49, 'Travel_Frequently', 1023, ..., 6, 0, 8],
       [34, 'Travel_Rarely', 628, ..., 3, 1, 2]], dtype=object)

In [15]:
from sklearn.preprocessing import LabelEncoder# label encode attrition
lb=LabelEncoder()
y[:,-1]=lb.fit_transform(y[:,-1])

In [16]:
y

array([[1],
       [0],
       [1],
       ...,
       [0],
       [0],
       [0]], dtype=object)

In [17]:
x[:,1]
ds.BusinessTravel.unique()

array(['Travel_Rarely', 'Travel_Frequently', 'Non-Travel'], dtype=object)

In [18]:
from sklearn.compose import ColumnTransformer# one hot encode travel
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer([('oh',OneHotEncoder(),[1])],remainder="passthrough")

In [19]:
x=ct.fit_transform(x)
x=x[:,1:]
x

array([[0.0, 1.0, 41, ..., 4, 0, 5],
       [1.0, 0.0, 49, ..., 7, 1, 7],
       [0.0, 1.0, 37, ..., 0, 0, 0],
       ...,
       [0.0, 1.0, 27, ..., 2, 0, 3],
       [1.0, 0.0, 49, ..., 6, 0, 8],
       [0.0, 1.0, 34, ..., 3, 1, 2]], dtype=object)

In [20]:
x.shape

(1470, 35)

In [21]:
ds.Department.unique()
#x[:,4]

array(['Sales', 'Research & Development', 'Human Resources'], dtype=object)

In [22]:
ct=ColumnTransformer([('oh',OneHotEncoder(),[4])],remainder="passthrough") #one hot encode department
x=ct.fit_transform(x)
x=x[:,1:]
x

array([[0.0, 1.0, 0.0, ..., 4, 0, 5],
       [1.0, 0.0, 1.0, ..., 7, 1, 7],
       [1.0, 0.0, 0.0, ..., 0, 0, 0],
       ...,
       [1.0, 0.0, 0.0, ..., 2, 0, 3],
       [0.0, 1.0, 1.0, ..., 6, 0, 8],
       [1.0, 0.0, 0.0, ..., 3, 1, 2]], dtype=object)

In [23]:
x.shape

(1470, 36)

In [24]:
ds.EducationField.unique()
#x[:,8]

array(['Life Sciences', 'Other', 'Medical', 'Marketing',
       'Technical Degree', 'Human Resources'], dtype=object)

In [25]:
ct=ColumnTransformer([('oh',OneHotEncoder(),[8])],remainder="passthrough") #one hot encode education
x=ct.fit_transform(x)
x=x[:,1:]
x


array([[1.0, 0.0, 0.0, ..., 4, 0, 5],
       [1.0, 0.0, 0.0, ..., 7, 1, 7],
       [0.0, 0.0, 0.0, ..., 0, 0, 0],
       ...,
       [1.0, 0.0, 0.0, ..., 2, 0, 3],
       [0.0, 0.0, 1.0, ..., 6, 0, 8],
       [0.0, 0.0, 1.0, ..., 3, 1, 2]], dtype=object)

In [26]:
x.shape

(1470, 40)

In [27]:
x[:,16]

array(['Female', 'Male', 'Male', ..., 'Male', 'Male', 'Male'],
      dtype=object)

In [28]:
lb=LabelEncoder() #LABEL ENCODE GENDER
x[:,16]=lb.fit_transform(x[:,16])

In [29]:
x[:,16]

array([0, 1, 1, ..., 1, 1, 1], dtype=object)

In [30]:
ds.JobRole.unique()
x[:,20]

array(['Sales Executive', 'Research Scientist', 'Laboratory Technician',
       ..., 'Manufacturing Director', 'Sales Executive',
       'Laboratory Technician'], dtype=object)

In [31]:
ct=ColumnTransformer([('oh',OneHotEncoder(),[20])],remainder="passthrough") #one hot encode education
x=ct.fit_transform(x)
x=x[:,1:]
x



array([[0.0, 0.0, 0.0, ..., 4, 0, 5],
       [0.0, 0.0, 0.0, ..., 7, 1, 7],
       [0.0, 1.0, 0.0, ..., 0, 0, 0],
       ...,
       [0.0, 0.0, 0.0, ..., 2, 0, 3],
       [0.0, 0.0, 0.0, ..., 6, 0, 8],
       [0.0, 1.0, 0.0, ..., 3, 1, 2]], dtype=object)

In [32]:
x[:,29]

array(['Single', 'Married', 'Single', ..., 'Married', 'Married',
       'Married'], dtype=object)

In [33]:
ct=ColumnTransformer([('oh',OneHotEncoder(),[29])],remainder="passthrough") #one hot encode marital status
x=ct.fit_transform(x)
x=x[:,1:]
x



array([[0.0, 1.0, 0.0, ..., 4, 0, 5],
       [1.0, 0.0, 0.0, ..., 7, 1, 7],
       [0.0, 1.0, 0.0, ..., 0, 0, 0],
       ...,
       [1.0, 0.0, 0.0, ..., 2, 0, 3],
       [1.0, 0.0, 0.0, ..., 6, 0, 8],
       [1.0, 0.0, 0.0, ..., 3, 1, 2]], dtype=object)

In [38]:
x[:,34]

array([1, 0, 1, ..., 1, 0, 0], dtype=object)

In [35]:
x=np.delete(x,34,1) #delete over 18 since all are above 18

In [37]:
lb=LabelEncoder() #LABEL ENCODE overtime
x[:,34]=lb.fit_transform(x[:,34])

In [39]:
ds.StandardHours.unique()

array([80])

In [42]:
x[:,38]

array([0, 1, 0, ..., 1, 0, 0], dtype=object)

In [41]:
x=np.delete(x,38,1) #delete standard hours since all 80

In [43]:
x.shape

(1470, 46)

In [44]:
x[:,45:]

array([[5],
       [7],
       [0],
       ...,
       [3],
       [8],
       [2]], dtype=object)

In [45]:
ds.EmployeeNumber.unique()

array([   1,    2,    4, ..., 2064, 2065, 2068])

In [46]:
x.shape

(1470, 46)

In [47]:
ds.EmployeeCount.unique()

array([1])

In [50]:
#delete employee count and emloyee number
x[:,23]

array([1, 2, 4, ..., 2064, 2065, 2068], dtype=object)

In [49]:
x=np.delete(x,23,1) 

In [51]:
x=np.delete(x,23,1) 

In [64]:
y=y.astype('int')

In [191]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=0)

In [195]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain=sc.fit_transform(xtrain)
xtest=sc.transform(xtest)

In [193]:
# from sklearn.tree import DecisionTreeClassifier 
# from sklearn.preprocessing import StandardScaler
# from sklearn.pipeline import Pipeline
# pipe=Pipeline([('r',StandardScaler()),('c',DecisionTreeClassifier(criterion='entropy',random_state=0))])
# pipe.fit(xtrain,ytrain)
# ypred=pipe.predict(xtest)
# from sklearn.metrics import accuracy_score
# accuracy_score(ytest,ypred)

0.7653061224489796

In [186]:
from sklearn.linear_model import LogisticRegression #logistic regression
lr=LogisticRegression()
lr.fit(xtrain,ytrain.ravel())
ypred=lr.predict(xtest)

In [187]:
from sklearn.metrics import accuracy_score
accuracy_score(ytest,ypred)

0.8843537414965986

In [123]:
# from sklearn.tree import DecisionTreeClassifier
# dt=DecisionTreeClassifier(criterion='entropy',random_state=0)
# dt.fit(xtrain,ytrain)
# ypred=dt.predict(xtest)

In [124]:
# from sklearn.metrics import accuracy_score
# accuracy_score(ytest,ypred)

0.7653061224489796

In [184]:
# from sklearn.ensemble import RandomForestClassifier
# rf=RandomForestClassifier(n_estimators=20,max_depth=5,random_state=0)
# rf.fit(xtrain,ytrain.ravel())
# ypred=rf.predict(xtest)


In [185]:
# from sklearn.metrics import accuracy_score
# accuracy_score(ytest,ypred)

0.8503401360544217

In [182]:
# from sklearn.neighbors import KNeighborsClassifier
# kn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
# kn.fit(xtrain,ytrain.ravel())
# ypred=kn.predict(xtest)


In [183]:
# from sklearn.metrics import accuracy_score
# accuracy_score(ytest,ypred)

0.8537414965986394

In [188]:
# from sklearn.naive_bayes import GaussianNB
# nb=GaussianNB()
# nb.fit(xtrain,ytrain.ravel())
# ypred=nb.predict(xtest)

In [189]:
# from sklearn.metrics import accuracy_score
# accuracy_score(ytest,ypred)

0.6530612244897959

In [198]:
# from sklearn.svm import SVC
# sv=SVC(kernel='rbf')
# sv.fit(xtrain,ytrain.ravel())
# ypred=sv.predict(xtest)

In [199]:
# from sklearn.metrics import accuracy_score
# accuracy_score(ytest,ypred)

0.8673469387755102